// SPDX-FileCopyrightText: © Hewlett Packard Enterprise Development LP
// SPDX-License-Identifier: Apache-2.0
import fs from 'fs';
import { simpleGit } from 'simple-git';
import pkg from '../package.json';

const git = simpleGit();

async function run() {
  let { version } = pkg;

  if (!process.env.CI) {
    const hash = (await git.revparse(['--short', 'HEAD'])).trim();
    const status = await git.status();
    const dirty = status.files.length > 0 ? '+dirty' : '';
    version = `${version}-local.${hash}${dirty}`;
  }

  const output = `// Auto-generated by tools/generate-version.js — do not edit.\nexport const themeVersion = ${JSON.stringify(version)};\n`;
  fs.writeFileSync('./src/js/themes/themeVersion.js', output);
  // eslint-disable-next-line no-console
  console.log('themeVersion:', version);
}

run();
